<a href="https://colab.research.google.com/github/michpach79/data-science-bootcamp/blob/main/02_algebra_liniowa_Michal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
v1=np.array([-1, 4])

In [ ]:
np.linalg.norm(v1)

4.123105625617661

In [ ]:
v2=np.array([-10, 10, 13])

In [ ]:
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p=np.array([3, 0])

In [ ]:
q=np.array([0, 4])

In [ ]:
np.linalg.norm(p-q)

5.0

In [ ]:
p=np.array([3, 0, 1])
q=np.array([0, 4, 2])

In [ ]:
np.linalg.norm(p-q)

5.0990195135927845

In [ ]:
x = np.array([[5, 3],[3, 9]])
y = np.array([[1],[-1]])

In [ ]:
print (x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
z = np.dot(x, y)
z

array([[ 2],
       [-6]])

In [ ]:
z.shape

(2, 1)

In [ ]:
x = np.array([[2, -1, 3],
              [3, 1, 0]])
y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(x, '\n')
print(y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
z = np.dot(x, y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [ ]:
z.shape

(2, 3)

In [ ]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

In [ ]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [ ]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
B = np.linalg.inv(A)

In [ ]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [2]:
A = np.array([[2, 4],[1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [4]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [5]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [6]:
X

array([[1.],
       [2.]])